//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_DataBase_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int E_Id { get; set; }
        public string E_Name { get; set; }
        public string E_Role { get; set; }
    }
}
